name: CI/CD
on:
  push:
    branches:
      - main
permissions:
  contents: write
  discussions: write
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    name: Build, test, deploy to docker hub and release
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: ${PWD}/scripts/build daa
      - name: Test
        run: ${PWD}/scripts/test daa
      - name: Trigger test-passed event in first repo
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: Tomcat-42/pydaa
          event-type: test-passed
